site_name: 重庆大学资源共享计划

theme:
  name: material
  features:
  - announce.dismiss
  - content.code.copy
  - navigation.footer
  - navigation.indexes
  - navigation.tabs
  - navigation.tabs.sticky
  palette:
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - scheme: defalt
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: indigo
    accent: indigo
  language: zh
  logo: assets/openlib-logo.png
  icon:
    repo: fontawesome/brands/github

nav:
- 课程: 
  - 课程/index.md
  - 程序设计技术:
    - 程序设计技术（Python）: 课程/程序设计技术/程序设计技术（Python）.md
    - 程序设计技术（C++）: 课程/程序设计技术/程序设计技术（C++）.md
  - 大学化学: 课程/大学化学.md
  - 大学化学实验: 课程/大学化学实验.md
  - 大学物理: 课程/大学物理.md
  - 大学物理实验: 课程/大学物理实验.md
  - 电路原理: 课程/电路原理.md
  - 概率论与数理统计: 课程/概率论与数理统计.md
  - 高等代数: 课程/高等代数.md
  - 高等数学: 课程/高等数学.md
  - 工程制图: 课程/工程制图.md
  - 管理学: 课程/管理学.md
  - 建筑类设计基础: 课程/建筑类设计基础.md
  - 金属学与热处理: 课程/金属学与热处理.md
  - 经济学原理: 课程/经济学原理.md
  - 离散数学: 课程/离散数学.md
  - 马克思主义基本原理: 课程/马克思主义基本原理.md
  - 毛泽东思想概论: 课程/毛泽东思想概论.md
  - 数学分析: 课程/数学分析.md
  - 数字逻辑: 课程/数字逻辑.md
  - 思想道德与法治: 课程/思想道德与法治.md
  - 思想道德与法治实践: 课程/思想道德与法治实践.md
  - 体育: 
    - 散打: 课程/体育/散打.md
  - 文明经典:
    - 课程/文明经典/index.md
    - 文明经典 A: 课程/文明经典/文明经典 A.md
    - 文明经典 B: 课程/文明经典/文明经典 B.md
  - 习近平法治思想概论: 课程/习近平法治思想概论.md
  - 线性代数: 课程/线性代数.md
  - 信号与系统: 课程/信号与系统.md
  - 英语: 课程/英语.md
  - 运筹学: 课程/运筹学.md
  - 中国近现代史纲要: 课程/中国近现代史纲要.md
- 学业: 
  - 学业/index.md
  - 专业总览:
    - 商科: 学业/专业总览/商科.md
  - 关于大类分流: 学业/关于大类分流.md
- 社团:
  - 社团/index.md
  - 学生社团中心:
    - 社团/学生社团中心/index.md
  - 直属社团:
    - 社团/直属社团/index.md
    - 时新社: 社团/直属社团/时新社.md
    - 小橘灯心理协会: 社团/直属社团/小橘灯心理协会.md
  - 青年志愿者协会:
    - 社团/青年志愿者协会/index.md
    - 绿色青年志愿者服务队: 社团/青年志愿者协会/绿色青年志愿者服务队.md
  - 科学技术协会:
    - 社团/科学技术协会/index.md
    - 方程式赛车队: 社团/科学技术协会/方程式赛车队.md
    - 航模协会: 社团/科学技术协会/航模协会.md
    - 华为智能基座协会: 社团/科学技术协会/华为智能基座协会.md
    - 机器人爱好者协会: 社团/科学技术协会/机器人爱好者协会.md
    - 科幻协会: 社团/科学技术协会/科幻协会.md
    - 蓝盟: 社团/科学技术协会/蓝盟.md
    - 趣味物理学社: 社团/科学技术协会/趣味物理学社.md
    - 天文学社: 社团/科学技术协会/天文学社.md
    - 微软学生俱乐部: 社团/科学技术协会/微软学生俱乐部.md
    - 英语协会: 社团/科学技术协会/英语协会.md
  - 文联:
    - 社团/文联/index.md
    - 博雅剧社: 社团/文联/博雅剧社.md
    - 茶协会: 社团/文联/茶协会.md
    - 哥乐相声社: 社团/文联/哥乐相声社.md
    - 古琴社: 社团/文联/古琴社.md
    - 花卉协会: 社团/文联/花卉协会.md
    - 吉他协会: 社团/文联/吉他协会.md
    - 说唱社: 社团/文联/说唱社.md
    - “文渊阁”读书协会: 社团/文联/“文渊阁”读书协会.md
    - 心引力音乐社: 社团/文联/心引力音乐社.md
    - 学生英语戏剧社: 社团/文联/学生英语戏剧社.md
    - 翼遥动漫社: 社团/文联/翼遥动漫社.md
    - 折纸社: 社团/文联/折纸社.md
  - 体育协会:
    - 社团/体育协会/index.md
    - 户外素质拓展协会: 社团/体育协会/户外素质拓展协会.md
    - 经纬棋社: 社团/体育协会/经纬棋社.md
    - 排球社: 社团/体育协会/排球社.md
    - 桥牌协会: 社团/体育协会/桥牌协会.md
    - 武术协会: 社团/体育协会/武术协会.md
    - 自行车协会: 社团/体育协会/自行车协会.md
  - 职业发展协会:
    - 社团/职业发展协会/index.md
    - 模拟法庭协会: 社团/职业发展协会/模拟法庭协会.md
    - 外语演讲与辩论协会: 社团/职业发展协会/外语演讲与辩论协会.md
- 技巧:
  - 技巧/index.md
  - 「蓝盟」电脑维修: 技巧/「蓝盟」电脑维修.md
  - 关于epub文件: 技巧/关于epub文件.md
  - 课表: 技巧/课表.md
  - 校园网: 技巧/校园网.md
  - 学生卡: 技巧/学生卡.md
  - 多端文件互传: 技巧/多端文件互传.md
- 生活:
  - 生活/index.md
  - 吃饭！活着就是为了吃饭！: 生活/吃饭！活着就是为了吃饭！.md
  - 学习之余也要生活不是嘛: 生活/学习之余也要生活不是嘛.md
  - 学生团体:
    - 生活/学生团体/学生团体.md
    - 饭协: 生活/学生团体/饭协.md
    - 喵呜社: 生活/学生团体/喵呜社.md
    - 铳带日麻: 生活/学生团体/铳带日麻.md
- 限时活动:
  - 限时活动/index.md
  - 本科生院科创月 2024_Apr: 限时活动/本科生院科创月 2024_Apr.md
- 杂项:
  - 杂项/index.md
  - 2022级分流数据:
    - 电气信息类2022级分流评价: 杂项/2022级分流数据/电气信息类2022级分流评价.md
  - 文明经典写作题目:
    - 文明经典B历史写作题目: 杂项/文明经典写作题目/文明经典B历史写作题目.md
    - 文明经典A历史写作题目: 杂项/文明经典写作题目/文明经典A历史写作题目.md

repo_url: https://github.com/INFO-studio/CQU-openlib
repo_name: CQU-openlib

copyright: Copyright &copy; 2024 CQU-openlib Opensource Organization

extra: 
 generator: false

markdown_extensions:
- admonition
- def_list
- pymdownx.arithmatex:
    generic: true
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.keys
- pymdownx.mark
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde

extra_javascript:
- javascripts/katex.js
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
