site_name: 重庆大学资源共享计划

theme:
  name: material
  features:
  - announce.dismiss
  - content.code.copy
  - navigation.footer
  - navigation.indexes
  - navigation.tabs
  - navigation.tabs.sticky
  font:
    code: Fira Code
  palette:
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  - scheme: defalt
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: indigo
    accent: indigo
  language: zh
  logo: assets/openlib-logo.png
  icon:
    repo: fontawesome/brands/github
    publisher: material/book-edit

repo_url: https://github.com/INFO-studio/CQU-openlib
repo_name: CQU-openlib

copyright: Copyright &copy; 2024 CQU-openlib Opensource Community

plugins:
  - tags

extra: 
  analytics:
    provider: google
    property: G-0000000000
    feedback:
      title: 您对该页面是否还满意？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 有帮助
          data: 1
          note: >-
            感谢反馈！开心喵
        - icon: material/emoticon-sad-outline
          name: 没帮助
          data: 0
          note: >- 
            感谢反馈（哭）<br>您可以提交 <a href="https://forms.office.com/r/4Wb8vu77GR?rc6e1d6688c2441c6a2158f000e455944={url}" target="_blank">表单</a> 来帮助我们改进！<br>拜托了
  generator: false
  tags:
    Publisher: publisher

markdown_extensions:
- admonition
- attr_list
- def_list
- md_in_html
- pymdownx.arithmatex:
    generic: true
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.keys
- pymdownx.mark
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
- toc: 
    permalink: true
    permalink_title: 小节签

extra_javascript:
- javascripts/katex.js
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

nav:
- 课程: 
  - 课程/index.md
  - 20世纪中国文艺思潮: 课程/20世纪中国文艺思潮.md
  - An Introduction to Machine Learning: 课程/An Introduction to Machine Learning.md
  - JAVA企业级应用: 课程/JAVA企业级应用.md
  - Java EE程序设计: 课程/Java EE程序设计.md
  - JAVA企业级应用: 课程/JAVA企业级应用.md
  - Linux操作系统: 课程/Linux操作系统.md
  - Numerical Methods For Engineers: 课程/Numerical Methods For Engineers.md
  - Web安全技术: 课程/Web安全技术.md
  - Web开发技术: 课程/Web开发技术.md
  - Windows应用程序原理: 课程/Windows应用程序原理.md
  - 《储能原理与技术》课程设计: 课程/《储能原理与技术》课程设计.md
  - 《大规模化学储能技术》课程设计: 课程/《大规模化学储能技术》课程设计.md
  - 《多能互联互补能源产储用系统及理论》课程设计: 课程/《多能互联互补能源产储用系统及理论》课程设计.md
  - 《能源转化原理》课程设计: 课程/《能源转化原理》课程设计.md
  - 《热能存储技术与应用》课程设计: 课程/《热能存储技术与应用》课程设计.md
  - 《世说新语》精读: 课程/《世说新语》精读.md
  - 程序设计技术:
    - 课程/程序设计技术/index.md
    - 程序设计技术（Python）: 课程/程序设计技术/程序设计技术（基于Python）.md
    - 程序设计技术（C++）: 课程/程序设计技术/程序设计技术（基于C++）.md
    - 程序设计技术（C）: 课程/程序设计技术/程序设计技术（基于C）.md
  - 储能材料科学基础: 课程/储能材料科学基础.md
  - 储能器件及关键材料: 课程/储能器件及关键材料.md
  - 储能系统安全管理: 课程/储能系统安全管理.md
  - 储能原理与技术: 课程/储能原理与技术.md
  - 储能专业综合实验: 课程/储能专业综合实验.md
  - 储氢技术及应用: 课程/储氢技术及应用.md
  - 大学化学: 课程/大学化学.md
  - 大学化学实验: 课程/大学化学实验.md
  - 大规模化学储能技术: 课程/大规模化学储能技术.md
  - 大数据计算: 课程/大数据计算.md
  - 大数据架构与技术: 课程/大数据架构与技术.md
  - 大数据生产实习: 课程/大数据生产实习.md
  - 大数据与智能运维: 课程/大数据与智能运维.md
  - 大学物理: 课程/大学物理.md
  - 大学物理实验: 课程/大学物理实验.md
  - 大型循环流化床燃烧技术: 课程/大型循环流化床燃烧技术.md
  - 电路原理: 课程/电路原理.md
  - 电子电工学: 课程/电子电工学.md
  - 电力储存技术与系统: 课程/电力储存技术与系统.md
  - 电力电子技术: 课程/电力电子技术.md
  - 电力系统分析: 课程/电力系统分析.md
  - 电动力学: 课程/电动力学.md
  - 电化学原理: 课程/电化学原理.md
  - 电化学测量: 课程/电化学测量.md
  - 电厂燃运与灰渣处理系统: 课程/电厂燃运与灰渣处理系统.md
  - 电子安装实习: 课程/电子安装实习.md
  - 电子综合设计及制作实践: 课程/电子综合设计及制作实践.md
  - 电工电子学: 课程/电工电子学.md
  - 电机学及拖动基础: 课程/电机学及拖动基础.md
  - 电机拖动与运动控制系统: 课程/电机拖动与运动控制系统.md
  - 电气工程综合设计: 课程/电气工程综合设计.md
  - 电液伺服控制: 课程/电液伺服控制.md
  - 电源技术: 课程/电源技术.md
  - 电磁场原理: 课程/电磁场原理.md
  - 复变函数: 课程/复变函数.md
  - 核安全前沿: 课程/核安全前沿.md
  - 核反应堆安全学: 课程/核反应堆安全学.md
  - 核反应堆控制: 课程/核反应堆控制.md
  - 核反应堆设计原理: 课程/核反应堆设计原理.md
  - 核工程前沿: 课程/核工程前沿.md
  - 核医学仪器与方法: 课程/核医学仪器与方法.md
  - 概率论与数理统计: 课程/概率论与数理统计.md
  - 高等数学: 课程/高等数学.md
  - 工程材料: 课程/工程材料.md
  - 工程测控技术: 课程/工程测控技术.md
  - 工程传质: 课程/工程传质.md
  - 工程电子技术: 课程/工程电子技术.md
  - 工程计算方法: 课程/工程计算方法.md
  - 工程经济学: 课程/工程经济学.md
  - 工程力学: 课程/工程力学.md
  - 工程热力学实验: 课程/工程热力学实验.md
  - 工程统计学: 课程/工程统计学.md
  - 工程项目管理: 课程/工程项目管理.md
  - 工程制图: 课程/工程制图.md
  - 工业催化: 课程/工业催化.md
  - 工业大数据与深度学习: 课程/工业大数据与深度学习.md
  - 工业大数据与深度学习课程设计: 课程/工业大数据与深度学习课程设计.md
  - 工业热力设备及系统: 课程/工业热力设备及系统.md
  - 离散数学: 课程/离散数学.md
  - 理想国: 课程/理想国.md
  - 量子力学: 课程/量子力学.md
  - 量子化学基础: 课程/量子化学基础.md
  - 量子化学实践: 课程/量子化学实践.md
  - 马克思主义基本原理: 课程/马克思主义基本原理.md
  - 毛泽东思想和中国特色社会主义理论体系概论: 课程/毛泽东思想和中国特色社会主义理论体系概论.md
  - 毛泽东思想和中国特色社会主义理论体系概论实践: 课程/毛泽东思想和中国特色社会主义理论体系概论实践.md
  - 普通物理: 课程/普通物理.md
  - 生产实习: 课程/生产实习.md
  - 生产系统建模与仿真: 课程/生产系统建模与仿真.md
  - 生产运作管理: 课程/生产运作管理.md
  - 生机电一体化: 课程/生机电一体化.md
  - 生物燃气制取原理与技术: 课程/生物燃气制取原理与技术.md
  - 生物质能利用新技术: 课程/生物质能利用新技术.md
  - 数据仓库与数据挖掘: 课程/数据仓库与数据挖掘.md
  - 数据结构: 课程/数据结构.md
  - 数据结构与算法: 课程/数据结构与算法.md
  - 数据科学导论: 课程/数据科学导论.md
  - 数据可视化: 课程/数据可视化.md
  - 数据库技术: 课程/数据库技术.md
  - 数据库原理及其应用: 课程/数据库原理及其应用.md
  - 数据库原理与设计: 课程/数据库原理与设计.md
  - 数据库系统: 课程/数据库系统.md
  - 数据驱动的控制与决策: 课程/数据驱动的控制与决策.md
  - 数据挖掘: 课程/数据挖掘.md
  - 数控加工实践: 课程/数控加工实践.md
  - 数学实验: 课程/数学实验.md
  - 数值计算与最优化: 课程/数值计算与最优化.md
  - 数字电路技术与设计实验: 课程/数字电路技术与设计实验.md
  - 数字动画与游戏设计: 课程/数字动画与游戏设计.md
  - 数字可视化: 课程/数字可视化.md
  - 数字图像处理: 课程/数字图像处理.md
  - 数字信号处理: 课程/数字信号处理.md
  - 机床数控技术: 课程/机床数控技术.md
  - 机电创新实践: 课程/机电创新实践.md
  - 机电控制原理与系统设计: 课程/机电控制原理与系统设计.md
  - 机电专业实验: 课程/机电专业实验.md
  - 机器人操作系统: 课程/机器人操作系统.md
  - 机器人技术前沿: 课程/机器人技术前沿.md
  - 机器人控制技术: 课程/机器人控制技术.md
  - 机器人系统设计及应用: 课程/机器人系统设计及应用.md
  - 机器人先进控制技术: 课程/机器人先进控制技术.md
  - 机器人学: 课程/机器人学.md
  - 机器人学基础: 课程/机器人学基础.md
  - 机器人与控制: 课程/机器人与控制.md
  - 机器人专业实验: 课程/机器人专业实验.md
  - 机器视觉: 课程/机器视觉.md
  - 机器学习: 课程/机器学习.md
  - 机器学习基础: 课程/机器学习基础.md
  - 机械储能原理与技术: 课程/机械储能原理与技术.md
  - 机械创新实践: 课程/机械创新实践.md
  - 机械电气控制及自动化: 课程/机械电气控制及自动化.md
  - 机械工程专业外语: 课程/机械工程专业外语.md
  - 机械基础实验: 课程/机械基础实验.md
  - 机械设计: 课程/机械设计.md
  - 机械设计基础: 课程/机械设计基础.md
  - 机械设计基础课程设计: 课程/机械设计基础课程设计.md
  - 机械设计综合实践: 课程/机械设计综合实践.md
  - 机械系统动力学: 课程/机械系统动力学.md
  - 机械原理: 课程/机械原理.md
  - 机械制图: 课程/机械制图.md
  - 机械制造技术基础: 课程/机械制造技术基础.md
  - 计算机仿真技术: 课程/计算机仿真技术.md
  - 计算机接口技术及应用: 课程/计算机接口技术及应用.md
  - 计算机视觉: 课程/计算机视觉.md
  - 计算机通讯与网络: 课程/计算机通讯与网络.md
  - 计算机图形学: 课程/计算机图形学.md
  - 计算机网络: 课程/计算机网络.md
  - 计算机网络安全: 课程/计算机网络安全.md
  - 计算机系统: 课程/计算机系统.md
  - 计算机硬件技术基础课程设计: 课程/计算机硬件技术基础课程设计.md
  - 计算机组成与结构: 课程/计算机组成与结构.md
  - 金工实习: 课程/金工实习.md
  - 面向对象技术与UML: 课程/面向对象技术与UML.md
  - 能源电化学: 课程/能源电化学.md
  - 能源动力过程中的环境保护: 课程/能源动力过程中的环境保护.md
  - 能源动力系统虚拟仿真创新实验: 课程/能源动力系统虚拟仿真创新实验.md
  - 能源工程材料: 课程/能源工程材料.md
  - 能源系统的评估原理: 课程/能源系统的评估原理.md
  - 能源战略与能源经济: 课程/能源战略与能源经济.md
  - 能源转化原理: 课程/能源转化原理.md
  - 热工学: 课程/热工学.md
  - 人工智能: 课程/人工智能.md
  - 人工智能基础: 课程/人工智能基础.md
  - 人工智能导论: 课程/人工智能导论.md
  - 人工智能技术与行业应用: 课程/人工智能技术与行业应用.md
  - 人工智能生产实习: 课程/人工智能生产实习.md
  - 人工智能课程设计: 课程/人工智能课程设计.md
  - 人机交互设计: 课程/人机交互设计.md
  - 软件测试: 课程/软件测试.md
  - 软件工程: 课程/软件工程.md
  - 软件工程导论: 课程/软件工程导论.md
  - 软件架构与设计模式: 课程/软件架构与设计模式.md
  - 软件逆向工程: 课程/软件逆向工程.md
  - 软件生产实习: 课程/软件生产实习.md
  - 软件项目管理: 课程/软件项目管理.md
  - 软件需求分析: 课程/软件需求分析.md
  - 软件综合设计: 课程/软件综合设计.md
  - 思想道德与法治: 课程/思想道德与法治.md
  - 思想道德与法治实践: 课程/思想道德与法治实践.md
  - 深度学习: 课程/深度学习.md
  - 深度学习实训: 课程/深度学习实训.md
  - 数学分析: 课程/数学分析.md
  - 数字电路技术与设计: 课程/数字电路技术与设计.md
  - 数字电子技术: 课程/数字电子技术.md
  - 数字逻辑: 课程/数字逻辑.md
  - 体育: 
    - 课程/体育/index.md
  - 微机原理与接口技术: 课程/微机原理与接口技术.md
  - 微纳测试与仪器: 课程/微纳测试与仪器.md
  - 微纳尺度能量输运和转换前沿: 课程/微纳尺度能量输运和转换前沿.md
  - 微生物能源转化技术: 课程/微生物能源转化技术.md
  - 微型计算机原理及接口技术: 课程/微型计算机原理及接口技术.md
  - 微型计算机原理及接口技术课程设计: 课程/微型计算机原理及接口技术课程设计.md
  - 文化与文明: 课程/文化与文明.md
  - 文化研究导论: 课程/文化研究导论.md
  - 文化研究经典选读: 课程/文化研究经典选读.md
  - 文明经典:
    - 课程/文明经典/index.md
    - 文明经典 A: 课程/文明经典/文明经典 A.md
    - 文明经典 B: 课程/文明经典/文明经典 B.md
  - 文学理论: 课程/文学理论.md
  - 习近平新时代中国特色社会主义思想概论: 课程/习近平新时代中国特色社会主义思想概论.md
  - 系统工程学: 课程/系统工程学.md
  - 现代材料测试分析方法: 课程/现代材料测试分析方法.md
  - 现代汉语: 课程/现代汉语.md
  - 现代控制工程: 课程/现代控制工程.md
  - 现代密码学: 课程/现代密码学.md
  - 线性代数: 课程/线性代数.md
  - 信号与系统: 课程/信号与系统.md
  - 信息安全导论: 课程/信息安全导论.md
  - 信息安全数学基础: 课程/信息安全数学基础.md
  - 信息论基础: 课程/信息论基础.md
  - 信息融合与控制: 课程/信息融合与控制.md
  - 信息隐藏技术: 课程/信息隐藏技术.md
  - 形势与政策: 课程/形势与政策.md
  - 英语: 课程/英语.md
  - 有机化学: 课程/有机化学.md
  - 有机化学实验: 课程/有机化学实验.md
  - 振动信号处理与结构系统辨识: 课程/振动信号处理与结构系统辨识.md
  - 制冷及低温原理: 课程/制冷及低温原理.md
  - 制冷压缩机: 课程/制冷压缩机.md
  - 制冷与空调前沿: 课程/制冷与空调前沿.md
  - 制冷系统设计及控制: 课程/制冷系统设计及控制.md
  - 制造技术: 课程/制造技术.md
  - 智慧工厂规划: 课程/智慧工厂规划.md
  - 智慧热力发电厂: 课程/智慧热力发电厂.md
  - 智能电器与工厂电气控制技术: 课程/智能电器与工厂电气控制技术.md
  - 智能感知与大数据管理: 课程/智能感知与大数据管理.md
  - 智能故障诊断技术与应用: 课程/智能故障诊断技术与应用.md
  - 智能机器人系统: 课程/智能机器人系统.md
  - 智能交通系统: 课程/智能交通系统.md
  - 智能控制基础: 课程/智能控制基础.md
  - 智能产品创新实践: 课程/智能产品创新实践.md
  - 智能无人系统: 课程/智能无人系统.md
  - 智能系统: 课程/智能系统.md
  - 智能系统创新实践: 课程/智能系统创新实践.md
  - 智能信息系统: 课程/智能信息系统.md
  - 智能运维: 课程/智能运维.md
  - 智能制造技术基础与应用: 课程/智能制造技术基础与应用.md
  - 智能制造数字化建模与仿真: 课程/智能制造数字化建模与仿真.md
  - 智能制造与数字工厂: 课程/智能制造与数字工厂.md
  - 智能制造专业综合课程设计: 课程/智能制造专业综合课程设计.md
  - 智能制造综合创新实践: 课程/智能制造综合创新实践.md
  - 智能装备与物联网: 课程/智能装备与物联网.md
  - 中国当代文学: 课程/中国当代文学.md
  - 中国古代文化史: 课程/中国古代文化史.md
  - 中国古代文学: 课程/中国古代文学.md
  - 中国近现代史纲要: 课程/中国近现代史纲要.md
  - 中国西南与东南亚: 课程/中国西南与东南亚.md
  - 中国现代文学: 课程/中国现代文学.md
  - 中国现代文学专题: 课程/中国现代文学专题.md
  - 中国现当代乡土文学研究: 课程/中国现当代乡土文学研究.md
  - 自动化工程设计基础: 课程/自动化工程设计基础.md
  - 自动控制原理: 课程/自动控制原理.md
  - 自动控制原理课程设计: 课程/自动控制原理课程设计.md
  - 自动驾驶与智慧交通: 课程/自动驾驶与智慧交通.md
  - 自然语言处理: 课程/自然语言处理.md
  - 自适应控制导论: 课程/自适应控制导论.md
  - 自主导航与定位技术: 课程/自主导航与定位技术.md
  - 自主专业实践: 课程/自主专业实践.md
- 学业: 
  - 学业/index.md
  - 新入学必看: 学业/新入学必看.md
  - 专业培养方案:
    - 学业/专业培养方案/index.md
    - 本科生院:
      - 学业/专业培养方案/本科生院/index.md
      - 工科试验班（电气信息类）: 学业/专业培养方案/本科生院/工科试验班（电气信息类）.md
      - 工科试验班（新工科类）: 学业/专业培养方案/本科生院/工科试验班（新工科类）.md
      - 工科试验班（工程能源类）: 学业/专业培养方案/本科生院/工科试验班（工程能源类）.md
      - 工科试验班（环化与健康类、生化类、环境类）: 学业/专业培养方案/本科生院/工科试验班（环化与健康类、生化类、环境类）.md
      - 理科试验班（数学物理类）: 学业/专业培养方案/本科生院/理科试验班（数学物理类）.md
    - 博雅学院（高研院）:
      - 学业/专业培养方案/博雅学院（高研院）/index.md
      - 汉语言文学: 学业/专业培养方案/博雅学院（高研院）/汉语言文学.md
    - 材料科学与工程学院:
      - 学业/专业培养方案/材料科学与工程学院/index.md
    - 重庆大学-辛辛那提大学联合学院:
      - 学业/专业培养方案/重庆大学-辛辛那提大学联合学院/index.md
    - 大数据与软件学院:
      - 学业/专业培养方案/大数据与软件学院/index.md
      - 人工智能: 学业/专业培养方案/大数据与软件学院/人工智能.md
      - 软件工程: 学业/专业培养方案/大数据与软件学院/软件工程.md
      - 数据科学与大数据技术: 学业/专业培养方案/大数据与软件学院/数据科学与大数据技术.md
    - 电气工程学院:
      - 学业/专业培养方案/电气工程学院/index.md
    - 法学院:
      - 学业/专业培养方案/法学院/index.md
    - 公共管理学院:
      - 学业/专业培养方案/公共管理学院/index.md
    - 管理科学与房地产学院:
      - 学业/专业培养方案/管理科学与房地产学院/index.md
    - 光电工程学院:
      - 学业/专业培养方案/光电工程学院/index.md
    - 国家卓越工程师学院:
      - 学业/专业培养方案/国家卓越工程师学院/index.md
    - 航空航天学院:
      - 学业/专业培养方案/航空航天学院/index.md
    - 弘深学院:
      - 学业/专业培养方案/弘深学院/index.md
    - 化学化工学院:
      - 学业/专业培养方案/化学化工学院/index.md
    - 环境与生态学院:
      - 学业/专业培养方案/环境与生态学院/index.md
    - 机械与运载工程学院:
      - 学业/专业培养方案/机械与运载工程学院/index.md
      - 机器人工程（智能机器人方向）: 学业/专业培养方案/机械与运载工程学院/机器人工程（智能机器人方向）.md
      - 机械电子工程: 学业/专业培养方案/机械与运载工程学院/机械电子工程.md
      - 智能制造工程: 学业/专业培养方案/机械与运载工程学院/智能制造工程.md
    - 计算机学院:
      - 学业/专业培养方案/计算机学院/index.md
      - 计算机科学与技术: 学业/专业培养方案/计算机学院/计算机科学与技术.md
      - 计算机科学与技术（卓越）: 学业/专业培养方案/计算机学院/计算机科学与技术（卓越）.md
      - 物联网工程: 学业/专业培养方案/计算机学院/物联网工程.md
      - 信息安全: 学业/专业培养方案/计算机学院/信息安全.md
    - 建筑城规学院:
      - 学业/专业培养方案/建筑城规学院/index.md
    - 经济与工商管理学院:
      - 学业/专业培养方案/经济与工商管理学院/index.md
    - 马克思主义学院:
      - 学业/专业培养方案/马克思主义学院/index.md
    - 美视电影学院:
      - 学业/专业培养方案/美视电影学院/index.md
    - 能源与动力工程学院:
      - 学业/专业培养方案/能源与动力工程学院/index.md
      - 储能科学与工程: 学业/专业培养方案/能源与动力工程学院/储能科学与工程.md
    - 生命科学学院:
      - 学业/专业培养方案/生命科学学院/index.md
    - 生物工程学院:
      - 学业/专业培养方案/生物工程学院/index.md
    - 数学与统计学院:
      - 学业/专业培养方案/数学与统计学院/index.md
    - 体育学院:
      - 学业/专业培养方案/体育学院/index.md
    - 土木工程学院:
      - 学业/专业培养方案/土木工程学院/index.md
    - 外国语学院:
      - 学业/专业培养方案/外国语学院/index.md
    - 微电子与通信工程学院:
      - 学业/专业培养方案/微电子与通信工程学院/index.md
    - 物理学院:
      - 学业/专业培养方案/物理学院/index.md
    - 新闻学院:
      - 学业/专业培养方案/新闻学院/index.md
    - 药学院（创新药物研究中心）:
      - 学业/专业培养方案/药学院（创新药物研究中心）/index.md
    - 医学院:
      - 学业/专业培养方案/医学院/index.md
    - 艺术学院:
      - 学业/专业培养方案/艺术学院/index.md
    - 资源与安全学院:
      - 学业/专业培养方案/资源与安全学院/index.md
    - 自动化学院:
      - 学业/专业培养方案/自动化学院/index.md
      # - 机器人工程（智能与控制方向）: 学业/专业培养方案/自动化学院/机器人工程（智能与控制方向）.md
      - 自动化: 学业/专业培养方案/自动化学院/自动化.md
  - 竞赛:
    - 算法: 学业/竞赛/算法.md
    - 数学建模: 学业/竞赛/数学建模.md
  - CQU官网汇总: 学业/CQU官网汇总.md
  - 专业总览:
    - 数统:
      - 数统教材: 学业/专业总览/数统/数统教材.md
    - 商科: 学业/专业总览/商科.md
    - 计算机自学:
      - java从入门到入土: 学业/专业总览/计算机自学/java从入门到入土.md
- 社团:
  - 社团/index.md
  - 学生社团中心:
    - 社团/学生社团中心/index.md
  - 直属社团:
    - 社团/直属社团/index.md
    - 时新社: 社团/直属社团/时新社.md
    - 小橘灯心理协会: 社团/直属社团/小橘灯心理协会.md
  - 青年志愿者协会:
    - 社团/青年志愿者协会/index.md
    - 法律援助协会: 社团/青年志愿者协会/法律援助协会.md
    - 互助协会: 社团/青年志愿者协会/互助协会.md
    - 绿色青年志愿者服务队: 社团/青年志愿者协会/绿色青年志愿者服务队.md
    - 唐仲英爱心协会: 社团/青年志愿者协会/唐仲英爱心协会.md
    - 向阳爱心社: 社团/青年志愿者协会/向阳爱心社.md
  - 科学技术协会:
    - 社团/科学技术协会/index.md
    - 电气电子工程师协会: 社团/科学技术协会/电气电子工程师协会.md
    - 方程式赛车队: 社团/科学技术协会/方程式赛车队.md
    - 硅藻智能材料协会: 社团/科学技术协会/硅藻智能材料协会.md
    - 航模协会: 社团/科学技术协会/航模协会.md
    - 华为智能基座协会: 社团/科学技术协会/华为智能基座协会.md
    - 机器人爱好者协会: 社团/科学技术协会/机器人爱好者协会.md
    - 建筑模型社: 社团/科学技术协会/建筑模型社.md
    - 科幻协会: 社团/科学技术协会/科幻协会.md
    - 蓝盟: 社团/科学技术协会/蓝盟.md
    - 趣味物理学社: 社团/科学技术协会/趣味物理学社.md
    - 天文学社: 社团/科学技术协会/天文学社.md
    - 微软学生俱乐部: 社团/科学技术协会/微软学生俱乐部.md
    - 英语协会: 社团/科学技术协会/英语协会.md
  - 文联:
    - 社团/文联/index.md
    - 博雅剧社: 社团/文联/博雅剧社.md
    - 茶协会: 社团/文联/茶协会.md
    - 哥乐相声社: 社团/文联/哥乐相声社.md
    - 古琴社: 社团/文联/古琴社.md
    - 花卉协会: 社团/文联/花卉协会.md
    - 吉他协会: 社团/文联/吉他协会.md
    - 书法协会: 社团/文联/书法协会.md
    - 说唱社: 社团/文联/说唱社.md
    - “文渊阁”读书协会: 社团/文联/“文渊阁”读书协会.md
    - 心引力音乐社: 社团/文联/心引力音乐社.md
    - 学生英语戏剧社: 社团/文联/学生英语戏剧社.md
    - 翼遥动漫社: 社团/文联/翼遥动漫社.md
    - 折纸社: 社团/文联/折纸社.md
  - 体育协会:
    - 社团/体育协会/index.md
    - 户外素质拓展协会: 社团/体育协会/户外素质拓展协会.md
    - 经纬棋社: 社团/体育协会/经纬棋社.md
    - 木野狐棋社: 社团/体育协会/木野狐棋社.md
    - 排球社: 社团/体育协会/排球社.md
    - 桥牌协会: 社团/体育协会/桥牌协会.md
    - 武术协会: 社团/体育协会/武术协会.md
    - 自行车协会: 社团/体育协会/自行车协会.md
  - 职业发展协会:
    - 社团/职业发展协会/index.md
    - 模拟法庭协会: 社团/职业发展协会/模拟法庭协会.md
    - 模拟联合国协会: 社团/职业发展协会/模拟联合国协会.md
    - 外语演讲与辩论协会: 社团/职业发展协会/外语演讲与辩论协会.md
    - 校企俱乐部: 社团/职业发展协会/校企俱乐部.md
    - 新奥精英社: 社团/职业发展协会/新奥精英社.md
- 技巧:
  - 技巧/index.md
  - 软件的下载安装、使用教程: 
    - VSCode下载并安装: 技巧/软件的下载安装、使用教程/VSCode下载与安装.md
    - Python下载与安装: 技巧/软件的下载安装、使用教程/Python下载与安装.md
    - FiraCode下载并安装: 技巧/软件的下载安装、使用教程/FiraCode下载与安装.md
    - pip安装Python库: 技巧/软件的下载安装、使用教程/pip安装Python库.md
    - Homebrew配置与使用: 技巧/软件的下载安装、使用教程/Homebrew配置与使用.md
    - conda管理Python环境: 技巧/软件的下载安装、使用教程/conda管理Python环境.md
    - 关于LaTeX: 技巧/软件的下载安装、使用教程/关于LaTeX.md
    - 关于SolidWorks: 技巧/软件的下载安装、使用教程/关于SolidWorks.md
  - 推荐使用的网站等:
    - 多端文件互传: 技巧/推荐使用的网站等/多端文件互传.md
    - 流程图: 技巧/推荐使用的网站等/流程图.md
    - 课表: 技巧/推荐使用的网站等/课表.md
    - 中国大学MOOC答案: 技巧/推荐使用的网站等/中国大学MOOC答案.md
  - 计算机基础:
    - 「蓝盟」电脑维修: 技巧/计算机基础/「蓝盟」电脑维修.md
    - 计算机基础: 技巧/计算机基础/计算机基础.md
    - 命令行基础: 技巧/计算机基础/命令行基础.md
    - 判断您的操作系统和系统架构: 技巧/计算机基础/判断您的操作系统和系统架构.md
    - 关于epub文件: 技巧/计算机基础/关于epub文件.md
    - 下载器: 技巧/计算机基础/下载器.md
- 生活:
  - 生活/index.md
  - 吃饭！活着就是为了吃饭！: 生活/吃饭！活着就是为了吃饭！.md
  - 学习之余也要生活不是嘛: 生活/学习之余也要生活不是嘛.md
  - 校园集市: 生活/校园集市.md
  - 校车时刻表: 生活/校车时刻表.md
  - 食堂菜单:
    - 虎溪校区一食堂: 生活/食堂菜单/虎溪校区一食堂.md
  - 学生团体:
    - 生活/学生团体/index.md
    - 铳带: 生活/学生团体/铳带.md
    - 电竞同好会: 生活/学生团体/电竞同好会.md
    - 东方Club: 生活/学生团体/东方Club.md
    - 饭协: 生活/学生团体/饭协.md
    - 喵呜社: 生活/学生团体/喵呜社.md
  - 校园网: 生活/校园网.md
  - 学生卡: 生活/学生卡.md
- 限时活动:
  - 限时活动/index.md
  - 本学期助教评教已开始: 限时活动/本学期助教评教已开始.md
- 贡献者: 
  - 贡献者/index.md
  - 茵符草: 贡献者/茵符草.md
  - xeri_chen: 贡献者/xeri_chen.md
  - 林欲静: 贡献者/林欲静.md
  - 叶旭航: 贡献者/叶旭航.md
  - Hacoj: 贡献者/Hacoj.md
- 杂项:
  - 杂项/index.md
  - 文明经典写作题目:
    - 文明经典B历史写作题目: 杂项/文明经典写作题目/文明经典B历史写作题目.md
    - 文明经典A历史写作题目: 杂项/文明经典写作题目/文明经典A历史写作题目.md
    - 221b1: 杂项/文明经典写作题目/2022届文明经典B上学期第一次写作题目.md
    - 221b2: 杂项/文明经典写作题目/2022届文明经典B上学期第二次写作题目.md
    - 221b3: 杂项/文明经典写作题目/2022届文明经典B上学期第三次写作题目.md
    - 221b4: 杂项/文明经典写作题目/2022届文明经典B上学期第四次写作题目.md
    - 221b5: 杂项/文明经典写作题目/2022届文明经典B上学期第五次写作题目.md
    - 221b6: 杂项/文明经典写作题目/2022届文明经典B上学期第六次写作题目.md
    - 231a1: 杂项/文明经典写作题目/2023届文明经典A上学期第一次写作题目.md
    - 231a1: 杂项/文明经典写作题目/2023届文明经典A下学期第一次写作题目.md
    - 231a2: 杂项/文明经典写作题目/2023届文明经典A上学期第二次写作题目.md
    - 231a3: 杂项/文明经典写作题目/2023届文明经典A上学期第三次写作题目.md
    - 231a4: 杂项/文明经典写作题目/2023届文明经典A上学期第四次写作题目.md
    - 231a5: 杂项/文明经典写作题目/2023届文明经典A上学期第五次写作题目.md
    - 232b1: 杂项/文明经典写作题目/2023届文明经典B下学期第一次写作题目.md